// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitEndingA(m MonsterParam, p PlayerParam) (EndingA, error) {
	player, err := NewPlayer(p)
	if err != nil {
		return EndingA{}, err
	}
	monster := NewMonster(m)
	endingA := NewEndingA(player, monster)
	return endingA, nil
}

func InitEndingB(m MonsterParam, p PlayerParam) (EndingB, error) {
	player, err := NewPlayer(p)
	if err != nil {
		return EndingB{}, err
	}
	monster := NewMonster(m)
	endingB := NewEndingB(player, monster)
	return endingB, nil
}
