// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitEndingA(m MonsterParam, p PlayerParam) (EndingA, error) {
	mainEndingA := EndingA{}
	return mainEndingA, nil
}

func InitEndingB(m MonsterParam, p PlayerParam) (EndingB, error) {
	mainEndingB := EndingB{}
	return mainEndingB, nil
}

// wire.go:

var monsterPlayerSet = wire.NewSet(NewMonster, NewPlayer)

var endingA = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingA)))

var endingB = wire.NewSet(monsterPlayerSet, wire.Struct(new(EndingB)))
